logging:
  level:
    root: info
    org.eclipse.jgit: info
    com.github.gnx: debug


server:
  port: 8080

spring:
  application:
    name: automate-server

  #数据库配置
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.1.190:3306/automate2?useSSL=false&useUnicode=true&characterEncoding=utf-8&autoReconnect=true&serverTimezone=Asia/Shanghai
    username: root
    password: 123456

  jpa:
    show-sql: true
    open-in-view: false
    properties:
      hibernate:
        format_sql: false

  # Redis数据库索引（默认为0）
  redis:
    database: 0
    # Redis服务器地址
    host: 192.168.1.190
    # Redis服务器连接端口
    port: 6379
    # Redis服务器连接密码（默认为空）
    password:

    jedis:
      pool:
        # 连接池最大连接数（使用负值表示没有限制）
        max-active: 8
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1
        # 连接池中的最大空闲连接
        max-idle: 8
        # 连接池中的最小空闲连接
        min-idle: 0
    # 连接超时时间（毫秒）
    timeout: 30000

automate:
  # 源码文件夹 默认 ./
  sourceCodeDir: 'E:/automate-data/sourcecode/'
  packageDir: 'E:/automate-data/package/'